### Probar conexion
GET http://localhost:1234/


### PARA SEPARAR LAS REQUEST DEBEMOS USAR LOS 3#
### NO USAR ; PORQUE ROMPEN TODO

###--------------------- RESERVAS --------------------

### Traer todas las reservas
GET http://localhost:1234/reservas/


### Traer reserva por id
GET http://localhost:1234/reservas/673f2715c394c2de1c0ad06d


### Eliminar reserva

DELETE http://localhost:1234/reservas/6718475f28bdd292f4fdbc8c


### Crear reserva
POST http://localhost:1234/reservas
Content-Type: application/json

{
  "nombreCliente": "Mauro Lobo",
  "email": "random@gmail.com",
  "fecha": "2024-11-23",
  "turno": "cena",
  "hora": "21:30",
  "cantidadPersonas": 2
}



###--------------------- MESAS --------------------

### CREAR MESAS
POST http://localhost:1234/mesas
Content-Type: application/json

{
  "capacidad": 5
}

### TRAER MESAS
GET http://localhost:1234/mesas
Content-Type: application/json


### TRAER MESA POR ID
### 
GET http://localhost:1234/mesas/673e999ff163abba03246a43
Content-Type: application/json



###--------------------- dias disponibles --------------------
GET http://localhost:1234/calendario/dias?turno=almuerzo&personas=2
Content-Type: application/json

### /dias/:fecha/horarios

###--------------------- horarios x fecha --------------------
GET http://localhost:1234/calendario/dias/2024-11-23/horarios?turno=cena&personas=2
Content-Type: application/json



###--------------------- AUTH --------------------

### Crear USUARIO e iniciar sesion
POST http://localhost:1234/auth/register
Content-Type: application/json

{
  "userName": "HernanSanta",
  "email": "hernansantarelli87@gmail.com"
}


### Cerrar sesión
GET http://localhost:1234/auth/logout
Content-Type: application/json
