### Probar conexion
GET http://localhost:1234/


### PARA SEPARAR LAS REQUEST DEBEMOS USAR LOS 3#
### NO USAR ; PORQUE ROMPEN TODO

###--------------------- RESERVAS --------------------

### Traer todas las reservas
GET http://localhost:1234/reservas/


### Traer reserva por id
GET http://localhost:1234/reservas/6748c6b20d829b8d4616c94b


### Eliminar reserva

DELETE http://localhost:1234/reservas/6718475f28bdd292f4fdbc8c


### Crear reserva
POST http://localhost:1234/reservas
Content-Type: application/json

{
  "fecha": "2024-11-29",
  "turno": "cena",
  "hora": "20:30",
  "cantidadPersonas": 2
}



###--------------------- MESAS --------------------

### CREAR MESAS
POST http://localhost:1234/mesas
Content-Type: application/json

{
  "capacidad": 5
}

### TRAER MESAS
GET http://localhost:1234/mesas
Content-Type: application/json


### TRAER MESA POR ID
### 
GET http://localhost:1234/mesas/673e999ff163abba03246a47
Content-Type: application/json



###--------------------- dias disponibles --------------------
GET http://localhost:1234/calendario/dias?turno=almuerzo&personas=2
Content-Type: application/json

### /dias/:fecha/horarios

###--------------------- horarios x fecha --------------------
GET http://localhost:1234/calendario/dias/2024-11-29/horarios?turno=cena&personas=2
Content-Type: application/json



###--------------------- AUTH --------------------

### Crear USUARIO e iniciar sesion
POST http://localhost:1234/auth/register
Content-Type: application/json

{
  "userName": "HernanSanta",
  "email": "hernansantarelli87@gmail.com"
}

### iniciar sesion
POST http://localhost:1234/auth/login
Content-Type: application/json

{
  "userName": "HernanSanta"
}

### Verificar link para iniciar sesion
GET http://localhost:1234/auth/login/verify?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDdhOWIwZDRlZjFmOGVkYWYzZGJlMSIsImxvZ2luVG9rZW4iOiIxMmNhNTIwMWM5MThmMGU5NDFkMTU2ZTdmNGI3YzRlMGE5MTc3NzczZGE5NDI4MmI3NTA1ZGFjNmEzYWY2OTc2IiwiaWF0IjoxNzMyODIyNTcxLCJleHAiOjE3MzI4MjM0NzF9.8ahPyhDPYoazMPwir3rpyCyWWSU4fuT3AXEULt-Lzuk
Content-Type: application/json


### Cerrar sesión
GET http://localhost:1234/auth/logout
Content-Type: application/json
